### ISSUE TITLE
Messages contain unwanted characters in case of assertion failure

### ISSUE THREAD

**Issue by harshit-bs** [nightwatchjs/nightwatch-inspector#11]
1. Ref : https://github.com/nightwatchjs/nightwatch/pull/3609#issuecomment-1450268260

   ![image](https://user-images.githubusercontent.com/94462364/222265282-196e27c3-34a4-4a05-97c7-8c9bdd5efaaa.png)

2. If the command's output message is [object, object] then convert it into a string.

**Comment by prudhvi22** [comment]
Closing this issue as it is fixed in https://github.com/harshit-bs/nightwatch/pull/9

**Comment by harshit-bs** [comment]
@prudhvi22 It seems 2 point is covered in this PR https://github.com/nightwatchjs/nightwatch-inspector/pull/20

**Comment by prudhvi22** [comment]
@harshit-bs Can we close this issue?
